export interface HivSummaryApiResponse {
    startIndex: string;
    size: number;
    result: HivSummary[];
    sql: string;
    sqlParams: (string | number)[];
}

export interface HivSummary {
    hpv_test_date: string | null;
    hpv: number | null;
    latest_vl_date: string | null;
    latest_vl: number | null;
    date_created: string;
    person_id: number;
    uuid: string;
    visit_id: number;
    visit_type: number;
    encounter_id: number;
    encounter_datetime: string;
    encounter_type: number;
    encounter_type_name: string;
    is_transit: number;
    is_clinical_encounter: number;
    location_id: number;
    last_non_transit_location_id: number;
    location_uuid: string;
    visit_num: number;
    mdt_session_number: number | null;
    enrollment_date: string;
    enrollment_location_id: number;
    ovc_non_enrollment_reason: number | null;
    ovc_non_enrollment_date: string | null;
    hiv_start_date: string;
    death_date: string | null;
    scheduled_visit: string | null;
    transfer_in: number | null;
    transfer_in_location_id: number | null;
    transfer_in_date: string | null;
    transfer_out: number | null;
    transfer_out_location_id: number | null;
    transfer_out_date: string | null;
    patient_care_status: number;
    out_of_care: number | null;
    prev_rtc_date: string | null;
    rtc_date: string | null;
    med_pickup_rtc_date: string | null;
    arv_first_regimen: string;
    arv_first_regimen_location_id: number;
    arv_first_regimen_start_date: string | null;
    arv_first_regimen_start_date_flex: string | null;
    prev_arv_meds: string | null;
    cur_arv_meds: string | null;
    cur_arv_meds_strict: string | null;
    cur_arv_drugs: string | null;
    prev_arv_drugs: string | null;
    arv_start_date: string | null;
    arv_start_location_id: number | null;
    prev_arv_start_date: string | null;
    prev_arv_end_date: string | null;
    prev_arv_line: number | null;
    cur_arv_line: number | null;
    cur_arv_line_strict: number | null;
    cur_arv_line_reported: number | null;
    prev_arv_adherence: string | null;
    cur_arv_adherence: string | null;
    hiv_status_disclosed: number | null;
    is_pregnant: number | null;
    edd: string | null;
    tb_screen: number | null;
    tb_screening_result: number | null;
    tb_screening_datetime: string | null;
    on_ipt: number | null;
    ipt_start_date: string | null;
    ipt_stop_date: string | null;
    ipt_completion_date: string | null;
    on_tb_tx: number | null;
    tb_tx_start_date: string | null;
    tb_tx_end_date: string | null;
    tb_tx_stop_date: string | null;
    pcp_prophylaxis_start_date: string | null;
    condoms_provided_date: string | null;
    modern_contraceptive_method_start_date: string | null;
    contraceptive_method: ContraceptiveMethod | null;
    menstruation_status: number | null;
    is_mother_breastfeeding: number | null;
    cur_who_stage: number | null;
    discordant_status: number | null;
    cd4_resulted: number | null;
    cd4_resulted_date: string | null;
    cd4_1: number | null;
    cd4_1_date: string | null;
    cd4_2: number | null;
    cd4_2_date: string | null;
    cd4_percent_1: number | null;
    cd4_percent_1_date: string | null;
    cd4_percent_2: number | null;
    cd4_percent_2_date: string | null;
    vl_resulted: number | null;
    vl_resulted_date: string | null;
    vl_1: number | null;
    vl_1_date: string | null;
    vl_2: number | null;
    vl_2_date: string | null;
    height: number | null;
    weight: number | null;
    expected_vl_date: number | null;
    vl_order_date: string | null;
    cd4_order_date: string | null;
    hiv_dna_pcr_order_date: string | null;
    hiv_dna_pcr_resulted: number | null;
    hiv_dna_pcr_resulted_date: string | null;
    hiv_dna_pcr_1: number | null;
    hiv_dna_pcr_1_date: string | null;
    hiv_dna_pcr_2: number | null;
    hiv_dna_pcr_2_date: string | null;
    hiv_rapid_test_resulted: number | null;
    hiv_rapid_test_resulted_date: string | null;
    prev_encounter_datetime_hiv: string | null;
    next_encounter_datetime_hiv: string | null;
    prev_encounter_type_hiv: number | null;
    next_encounter_type_hiv: number | null;
    prev_clinical_datetime_hiv: string | null;
    next_clinical_datetime_hiv: string | null;
    prev_clinical_location_id: number | null;
    next_clinical_location_id: number | null;
    prev_clinical_rtc_date_hiv: string | null;
    next_clinical_rtc_date_hiv: string | null;
    outreach_date_bncd: string | null;
    outreach_death_date_bncd: string | null;
    outreach_patient_care_status_bncd: number | null;
    transfer_date_bncd: string | null;
    transfer_transfer_out_bncd: number | null;
    phone_outreach: number | null;
    home_outreach: number | null;
    outreach_attempts: number | null;
    outreach_missed_visit_reason: number | null;
    travelled_outside_last_3_months: number | null;
    travelled_outside_last_6_months: number | null;
    travelled_outside_last_12_months: number | null;
    last_cross_boarder_screening_datetime: string | null;
    is_cross_border_country: number | null;
    cross_border_service_offered: number | null;
    cross_border_country_travelled: string | null;
    is_cross_border_county: number | null;
    is_cross_border: number | null;
    country_of_residence: string | null;
    ovc_exit_reason: number | null;
    ovc_exit_date: string | null;
    tb_tx_stop_reason: number | null;
    ca_cx_screen: number | null;
    ca_cx_screening_result: number | null;
    ca_cx_screening_result_datetime: string | null;
    ca_cx_screening_datetime: string | null;
    tb_modality_test: number | null;
    tb_test_result: number | null;
    tb_test_date: string | null;
    gbv_screening_result: number | null;
    on_modern_contraceptive: number | null;
    modern_contraceptive_reporting_date: string | null;
    continue_on_fp: number | null;
    with_pregnancy_intentions: number | null;
    transfer_out_date_type: number | null;
    tb_prophylaxis_duration: number | null;
    tb_prophylaxis_medication: string | null;
    outreach_result: number | null;
    patient_category: number | null;
    initiation_reason: number | null;
    discontinued_reason: number | null;
    hiv_disclosure_status_value: string | null;
    cm_result: number | null;
    cm_result_date: string | null;
    cm_test: number | null;
    cm_treatment_end_date: string | null;
    cm_treatment_phase: number | null;
    cm_treatment_start_date: string | null;
    cur_arv_meds_id: string | null;
    arv_first_regimen_id: string | null;
    prev_encounter_type_name: string | null;
}

export interface ContraceptiveMethod {
    concept: number;
    name: string;
    period: string | null;
}

export type HivSummaryParams = {
  patientUuid: string;
  startIndex:number;
  limit:number;
  includeNonClinicalEncounter: boolean;
  isHEIActive: boolean;
}